universe                = vanilla
executable              = /data/bfys/gscriven/LHCb_Extrapolation_Project/multi_network_chain_discrete_approach/Block_D_fixed_step_crossing/D1_Chain_grid/condor/wrapper_chain.sh
arguments               = $(args)

output                  = condor/logs/$(Cluster).$(Process).out
error                   = condor/logs/$(Cluster).$(Process).err
log                     = condor/logs/$(Cluster).log

request_cpus            = 1
request_memory          = 4096
should_transfer_files   = NO
getenv                  = False
+UseOS                  = "el9"
+JobCategory            = "medium"

queue args from condor/jobs_chain.txt
