#!/usr/bin/env python
"""E4 - every number the write-up quotes that is not already a cell of a results file.

Ratios, ranges, sums and two correlations, each computed from a named file so the page can
be checked line by line. Nothing here reads a network: the inputs are

  regen/results/*.csv                     the E3 tables regenerated by make_figures.py from
                                          the 2026-09-18 checkpoints (identical to
                                          ../E3_Analysis/results/*.csv where both exist)
  ../../Block_F_reweighted_loss/F2_Analysis/results/headline.csv
                                          the same sixteen runs after the extension, scored
                                          by the plateau rule (rows with weighting = blockE)
  ../../Block_F_reweighted_loss/F2_Analysis/results/anatomy_xy_blockE_*.json
                                          the two-slope anatomy of the extended runs
  ../E0_Track_dataset/results/tracks.npz  the tracks, for the starting-x correlation

Run:     PYTHONNOUSERSITE=1 /data/bfys/gscriven/conda/envs/TE/bin/python numbers.py
Outputs: results/numbers.json, and the same as a printed table
"""
from __future__ import annotations

import os
import sys

# This file is called numbers.py because the write-up plan names it so, and that shadows the
# standard library's `numbers` module, which numpy imports. Drop this folder from the import
# path before anything else is imported; the file itself is already loaded as __main__.
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or ".") != _HERE]

import csv     # noqa: E402
import glob    # noqa: E402
import json    # noqa: E402
import math    # noqa: E402

import numpy as np   # noqa: E402

HERE = _HERE
REGEN = os.path.join(HERE, "regen", "results")
F2 = os.path.abspath(os.path.join(HERE, "..", "..", "Block_F_reweighted_loss",
                                  "F2_Analysis", "results"))
TRACKS = os.path.abspath(os.path.join(HERE, "..", "E0_Track_dataset", "results", "tracks.npz"))


def rows(path):
    with open(path) as f:
        return list(csv.DictReader(f))


def rank(a):
    order = np.argsort(a, kind="mergesort")
    r = np.empty(len(a), dtype=np.float64)
    r[order] = np.arange(len(a), dtype=np.float64)
    # average ties
    a_sorted = np.asarray(a)[order]
    i = 0
    while i < len(a_sorted):
        j = i
        while j + 1 < len(a_sorted) and a_sorted[j + 1] == a_sorted[i]:
            j += 1
        if j > i:
            r[order[i:j + 1]] = np.mean(np.arange(i, j + 1))
        i = j + 1
    return r


def spearman(a, b):
    ra, rb = rank(np.asarray(a, float)), rank(np.asarray(b, float))
    ra = ra - ra.mean()
    rb = rb - rb.mean()
    return float((ra * rb).sum() / math.sqrt((ra * ra).sum() * (rb * rb).sum()))


def main():
    out = {}

    # ---- 1. the sixteen endpoints, as stopped on 2026-09-18 -------------------
    chain = {(int(r["N"]), int(r["q"])): r for r in rows(os.path.join(REGEN, "error_qdz_chain.csv"))}
    step = {(int(r["N"]), int(r["q"])): r for r in rows(os.path.join(REGEN, "error_qdz_single_step.csv"))}
    med = {k: float(v["med_um"]) for k, v in chain.items()}
    long_chains = {k: v for k, v in med.items() if k[0] >= 64}
    out["stopped_2026_09_18"] = dict(
        source="regen/results/error_qdz_chain.csv (= E3_Analysis/results/error_qdz_chain.csv)",
        all_sixteen_min_um=min(med.values()), all_sixteen_max_um=max(med.values()),
        N_at_least_64_min_um=min(long_chains.values()), N_at_least_64_max_um=max(long_chains.values()),
        N_at_least_64_min_at=min(long_chains, key=long_chains.get),
        N_at_least_64_max_at=max(long_chains, key=long_chains.get),
        exact_scheme_N_at_least_64_min_um=min(float(v["exact_med_um"]) for k, v in chain.items() if k[0] >= 64),
        exact_scheme_N_at_least_64_max_um=max(float(v["exact_med_um"]) for k, v in chain.items() if k[0] >= 64),
        n_test_tracks=int(chain[(64, 2)]["n"]),
    )

    # ---- 2. the same sixteen after the extension -----------------------------
    hl = [r for r in rows(os.path.join(F2, "headline.csv")) if r["weighting"] == "blockE"]
    hmed = {(int(r["N"]), int(r["q"])): float(r["test_radial_med_um"]) for r in hl}
    hlong = {k: v for k, v in hmed.items() if k[0] >= 64}
    band = {(int(r["N"]), int(r["q"])): float(r["test_radial_band_med_um"]) for r in hl}
    blong = {k: v for k, v in band.items() if k[0] >= 64}
    soft = {(int(r["N"]), int(r["q"])): float(r["test_radial_soft_med_um"]) for r in hl}
    wall = {(int(r["N"]), int(r["q"])): float(r["train_wall_h"]) for r in hl}
    restarts = {(int(r["N"]), int(r["q"])): int(r["restarts"]) for r in hl}
    rounds = {(int(r["N"]), int(r["q"])): int(r["rounds"]) for r in hl}
    plateaued = {(int(r["N"]), int(r["q"])): (r["plateaued_now"] == "True") for r in hl}
    spread = {(int(r["N"]), int(r["q"])): float(r["val_spread_pct"]) for r in hl}   # already a percent
    # N = 2, q = 2 was never extended (it sits at the exact scheme's own error), so its
    # plateau verdict is "not applicable", not "still improving".
    never_extended = (2, 2)
    out["extended"] = dict(
        source="Block_F_reweighted_loss/F2_Analysis/results/headline.csv, rows with weighting = blockE",
        n_runs=len(hl),
        N_at_least_64_min_um=min(hlong.values()), N_at_least_64_max_um=max(hlong.values()),
        N_at_least_64_min_at=min(hlong, key=hlong.get), N_at_least_64_max_at=max(hlong, key=hlong.get),
        band_10_50_GeV_min_um=min(blong.values()), band_10_50_GeV_max_um=max(blong.values()),
        band_min_at=min(blong, key=blong.get),
        below_5GeV_min_um=min(v for k, v in soft.items() if k[0] >= 64),
        below_5GeV_max_um=max(v for k, v in soft.items() if k[0] >= 64),
        improvement_over_the_stop_pct={"%d_%d" % k: round(100 * (hmed[k] - med[k]) / med[k], 1)
                                       for k in sorted(hmed)},
        restarts_min=min(restarts.values()), restarts_max=max(restarts.values()),
        rounds_min=min(rounds.values()), rounds_max=max(rounds.values()),
        wall_h_min=min(wall.values()), wall_h_max=max(wall.values()),
        wall_h_total=round(sum(wall.values()), 1),
        n_plateaued=sum(plateaued.values()),
        n_still_improving=sum(not v for k, v in plateaued.items() if k != never_extended),
        still_improving=["N = %d, q = %d" % k for k in sorted(plateaued)
                         if not plateaued[k] and k != never_extended],
        never_extended="N = %d, q = %d" % never_extended,
        val_spread_pct_min=round(min(spread.values()), 1), val_spread_pct_max=round(max(spread.values()), 1),
        val_spread_pct_min_N_at_least_64=round(min(v for k, v in spread.items() if k[0] >= 64), 1),
        val_spread_pct_max_N_at_least_64=round(max(v for k, v in spread.items() if k[0] >= 64), 1),
    )

    # ---- 3. one step, and the chain divided by it ----------------------------
    smed = {k: float(v["step_med_um"]) for k, v in step.items()}
    slong = {k: v for k, v in smed.items() if k[0] >= 64}
    ratio = {k: med[k] / smed[k] for k in med}
    out["single_step"] = dict(
        source="regen/results/error_qdz_single_step.csv; the ratio uses the radial endpoint median "
               "of error_qdz_chain.csv over the radial single-step median of the same run",
        N_at_least_64_min_um=min(slong.values()), N_at_least_64_max_um=max(slong.values()),
        fraction_of_the_straight_line_pct_min=100 * min(float(v["step_over_straight"])
                                                        for k, v in step.items() if k[0] >= 64),
        fraction_of_the_straight_line_pct_max=100 * max(float(v["step_over_straight"])
                                                        for k, v in step.items() if k[0] >= 64),
        chain_over_step={"%d_%d" % k: round(ratio[k], 1) for k in sorted(ratio)},
        chain_over_step_N_at_least_64_min=round(min(v for k, v in ratio.items() if k[0] >= 64), 0),
        chain_over_step_N_at_least_64_max=round(max(v for k, v in ratio.items() if k[0] >= 64), 0),
        step_below_5GeV_over_above_10GeV={"%d_%d" % k: round(float(v["step_med_um_p_below_5GeV"])
                                                            / float(v["step_med_um_p_above_10GeV"]), 2)
                                          for k, v in sorted(step.items())},
    )

    # ---- 4. growth along the crossing ----------------------------------------
    vz = rows(os.path.join(REGEN, "error_vs_z.csv"))
    growth = {}
    for (N, q) in [(64, 2), (128, 8), (256, 16)]:
        s = sorted([r for r in vz if int(r["N"]) == N and int(r["q"]) == q], key=lambda r: int(r["plane"]))
        qu, ha, en = s[N // 4], s[N // 2], s[N]
        growth["%d_%d" % (N, q)] = dict(quarter_um=float(qu["med_um"]), half_um=float(ha["med_um"]),
                                        end_um=float(en["med_um"]),
                                        end_over_half=round(float(en["med_um"]) / float(ha["med_um"]), 2),
                                        half_over_quarter=round(float(ha["med_um"]) / float(qu["med_um"]), 2))
    out["growth_along_z"] = dict(source="regen/results/error_vs_z.csv", per_run=growth)

    # ---- 5. where the loss is spent ------------------------------------------
    ls = rows(os.path.join(REGEN, "case_study_loss_vs_p.csv"))
    below5 = sum(float(r["loss_share"]) for r in ls if float(r["p_hi"]) <= 5)
    in2to5 = sum(float(r["loss_share"]) for r in ls if float(r["p_lo"]) >= 2 and float(r["p_hi"]) <= 5)
    above5 = sum(float(r["loss_share"]) for r in ls if float(r["p_lo"]) >= 5)
    in10to50 = sum(float(r["loss_share"]) for r in ls if float(r["p_lo"]) >= 10 and float(r["p_hi"]) <= 50)
    out["loss_share"] = dict(
        source="regen/results/case_study_loss_vs_p.csv (N = 64, q = 2)",
        share_2_to_5_GeV_pct=round(100 * in2to5, 1), share_below_5_GeV_pct=round(100 * below5, 1),
        share_above_5_GeV_pct=round(100 * above5, 1), share_10_to_50_GeV_pct=round(100 * in10to50, 2),
        n_tracks_2_to_5=sum(int(r["n"]) for r in ls if float(r["p_lo"]) >= 2 and float(r["p_hi"]) <= 5),
        n_tracks_above_5=sum(int(r["n"]) for r in ls if float(r["p_lo"]) >= 5),
    )

    # ---- 6. against the one-network-per-step chains --------------------------
    bd = {k: float(v["block_d_med_um"]) for k, v in chain.items()
          if v["block_d_med_um"] not in ("", "nan")}
    bd = {k: v for k, v in bd.items() if v == v}
    out["per_step_networks"] = dict(
        source="regen/results/error_qdz_chain.csv, column block_d_med_um (the earlier study's "
               "stored chain states, re-scored radially on the same test tracks)",
        ratio={"%d_%d" % k: round(bd[k] / med[k], 1) for k in sorted(bd)},
        ratio_min=round(min(bd[k] / med[k] for k in bd), 1),
        ratio_max=round(max(bd[k] / med[k] for k in bd), 1),
    )

    # ---- 7. over-training ----------------------------------------------------
    ot = rows(os.path.join(REGEN, "overtraining.csv"))
    tt = [float(r["test_over_train_pos"]) for r in ot]
    ll = [float(r["test_over_train_loss"]) for r in ot]
    out["over_training"] = dict(source="regen/results/overtraining.csv", n_runs=len(ot),
                                test_over_train_min=round(min(tt), 3), test_over_train_max=round(max(tt), 3),
                                test_over_train_median=round(float(np.median(tt)), 3),
                                loss_ratio_min=round(min(ll), 2), loss_ratio_max=round(max(ll), 2),
                                loss_ratio_median=round(float(np.median(ll)), 2))

    # ---- 8. the plateau rule as a coin-flip probability ----------------------
    out["eleven_of_eleven"] = dict(
        source="Block_F_reweighted_loss/F2_Analysis/README.md table (eleven runs with 20+ rounds "
               "at the stop of 2026-09-18), probability computed here",
        p_all_eleven_fall_if_noise=round(0.5 ** 11, 6))

    # ---- 9. the two-slope anatomy of the extended runs -----------------------
    ax = {}
    for p in sorted(glob.glob(os.path.join(F2, "anatomy_xy_blockE_*.json"))):
        d = json.load(open(p))
        ax["%d_%d" % (d["N"], d["q"])] = dict(
            explained_both_slopes=round(d["explained"]["both_slopes"], 3),
            explained_x_slope_only=round(d["explained"]["x_slope_only"], 3),
            explained_positions_only=round(d["explained"]["positions_only"], 3),
            x_part_um=round(d["x_part_med_um"], 1), y_part_um=round(d["y_part_med_um"], 1),
            coherence_tx=round(d["coherence"]["tx"], 3), coherence_ty=round(d["coherence"]["ty"], 3),
            per_step_tx_mrad=d["local_step"]["tx_mrad"], per_step_ty_mrad=d["local_step"]["ty_mrad"],
            final_med_um=round(d["final_med_um"], 1))
    out["anatomy_two_slopes_extended"] = dict(
        source="Block_F_reweighted_loss/F2_Analysis/results/anatomy_xy_blockE_*.json "
               "(the EXTENDED networks, not the 2026-09-18 checkpoints)", per_run=ax,
        explained_min=min(v["explained_both_slopes"] for v in ax.values()),
        explained_max=max(v["explained_both_slopes"] for v in ax.values()))

    # ---- 10. starting x and momentum ----------------------------------------
    D = np.load(TRACKS)
    S0 = np.asarray(D["test_S0"])
    P = np.asarray(D["test_P"])
    out["starting_x"] = dict(
        source="E0_Track_dataset/results/tracks.npz, test split, computed here",
        n=int(len(P)),
        spearman_x0_vs_p=round(spearman(np.abs(S0[:, 0]), P), 3),
        median_abs_x0_mm=round(float(np.median(np.abs(S0[:, 0]))), 1),
        p95_abs_x0_mm=round(float(np.quantile(np.abs(S0[:, 0]), 0.95)), 1))

    # ---- 11b. the endpoint error against the track's starting x ---------------
    # E3's case_study_3d.py bins the SIGNED x0 and works per component; the write-up quotes
    # the radial endpoint error against |x0|, pooled over both signs, so it is computed here
    # from the same stored chain states of the 2026-09-18 checkpoint.
    CASE = (64, 2)
    states = np.load(os.path.join(HERE, "runs_stopped_2026-09-18", "results",
                                  "N%03d_q%02d" % CASE, "chain_states.npz"))["test_states"]
    n_max = int(D["n_max"])
    truth_end = np.asarray(D["test_truth"])[:, n_max]
    r_end = np.hypot(states[:, -1, 0] - truth_end[:, 0], states[:, -1, 1] - truth_end[:, 1]) * 1e3
    absx0 = np.abs(S0[:, 0])
    edges = [0.0, 75.0, 150.0, 250.0, 400.0, 700.0]
    bands, bands_band = [], []
    inband = (P >= 10) & (P < 20)
    for lo, hi in zip(edges[:-1], edges[1:]):
        m = (absx0 >= lo) & (absx0 < hi)
        bands.append(dict(x0_lo_mm=lo, x0_hi_mm=hi, n=int(m.sum()),
                          med_um=round(float(np.median(r_end[m])), 1) if m.sum() else None))
        mb = m & inband
        bands_band.append(dict(x0_lo_mm=lo, x0_hi_mm=hi, n=int(mb.sum()),
                               med_um=round(float(np.median(r_end[mb])), 1) if mb.sum() >= 5 else None))
    ok = [b["med_um"] for b in bands if b["med_um"]]
    out["starting_x_bands"] = dict(
        source="runs_stopped_2026-09-18/results/N064_q02/chain_states.npz and "
               "E0_Track_dataset/results/tracks.npz, test split, computed here",
        network="N = %d, q = %d" % CASE, metric="radial endpoint error at z1 [µm], median",
        all_tracks=bands, band_10_20_GeV=bands_band,
        edge_over_centre=round(ok[-1] / ok[0], 1),
        median_over_all=round(float(np.median(r_end)), 1))

    # ---- 11c. the case study's error distribution by coarse momentum band -----
    # the three medians the overview figure prints in its legend
    coarse = []
    for lo, hi in ((1.0, 5.0), (5.0, 20.0), (20.0, 200.0)):
        m = (P >= lo) & (P < hi)
        coarse.append(dict(p_lo=lo, p_hi=hi, n=int(m.sum()),
                           med_um=round(float(np.median(r_end[m])), 1)))
    out["case_study_by_coarse_band"] = dict(
        source="the same stored chain states as starting_x_bands; these are the three medians "
               "printed in the legend of figures_writeup/case_study_overview.png",
        network="N = %d, q = %d" % CASE, bands=coarse)

    # ---- 11. cost -------------------------------------------------------------
    cost = rows(os.path.join(REGEN, "cost_accuracy.csv"))
    out["cost"] = dict(source="regen/results/cost_accuracy.csv",
                       us_per_track={"%s_%s" % (r["N"], r["q"]): float(r["us_per_track"]) for r in cost},
                       parameters={r["q"]: int(r["n_parameters"]) for r in cost})

    os.makedirs(os.path.join(HERE, "results"), exist_ok=True)
    with open(os.path.join(HERE, "results", "numbers.json"), "w") as f:
        json.dump(out, f, indent=1)
    print(json.dumps(out, indent=1))
    return out


if __name__ == "__main__":
    main()
