universe                = vanilla
executable              = /data/bfys/gscriven/LHCb_Extrapolation_Project/Raissi_disc_time_approach/Step_size_and_stage_grid/condor/wrapper_grid.sh
arguments               = $(args)

output                  = condor/logs/$(Cluster).$(Process).out
error                   = condor/logs/$(Cluster).$(Process).err
log                     = condor/logs/$(Cluster).log

request_cpus            = 1
request_memory          = $(mem)
should_transfer_files   = NO
getenv                  = False
+UseOS                  = "el9"
+JobCategory            = "medium"

queue mem, args from condor/jobs_grid.txt
